services:
  - type: web
    name: leaftalk-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://leaftalk-app.onrender.com
      - key: VITE_WS_BASE_URL
        value: wss://leaftalk-app.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
